### ISSUE TITLE
Spelling mistakes

### ISSUE THREAD

**Issue by benkasminbullock** [briandfoy/chemistry-elements#1]
Element 59 Praesodymium should be Praseodymium:

https://en.wikipedia.org/wiki/Praseodymium

Element 103 Lawerencium should be Lawrencium:

https://en.wikipedia.org/wiki/Lawrencium

These are in the pull request, but in case you decide not to accept that I'm pointing it out separately here.

**Comment by briandfoy** [comment]
Fixed in #2 (by you!). Thanks,

**Comment by briandfoy** [comment]
Released as 1.064.
